#!/usr/bin/env python3
"""Render display artifacts from jobs.yaml (v4)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from job_roles import PRIMARY_ROLES, REVIEW_ROLES
from jobs_store import JobsStoreError, is_v4_task, load_jobs
from model_resolve import load_task_state
from session_usage import markdown_row, resolve_time_cell

GENERATED_DIR = "generated"
GENERATED_HEADER = """<!--
Generated from jobs.yaml. Do not edit by hand.
Run: run-dp render {kind} --task-dir ...
-->
"""

MODEL_USAGE_HEADER = """# Model usage

**Generated from `jobs.yaml` (v4 Job Contract).** Do not edit this file by hand.

| Time | Stage id | Action | Profile / role | Preset / reasoning | Session | Model | Usage / cost | Evidence |
|------|----------|--------|----------------|-------------------|---------|-------|--------------|----------|
"""


def generated_dir(task_dir: Path) -> Path:
    d = task_dir / GENERATED_DIR
    d.mkdir(parents=True, exist_ok=True)
    return d


def default_model_usage_path(task_dir: Path) -> Path:
    return generated_dir(task_dir) / "model_usage.md"


def default_review_summary_path(task_dir: Path) -> Path:
    return generated_dir(task_dir) / "review_summary.md"


def _preset(state: dict[str, Any]) -> str:
    p = state.get("review_depth_preset")
    return str(p).strip() if isinstance(p, str) and p.strip() else "unknown"


def render_model_usage(task_dir: Path) -> str:
    data = load_jobs(task_dir)
    try:
        state = load_task_state(task_dir)
    except Exception:
        state = {}
    preset = _preset(state)
    lines = [GENERATED_HEADER.format(kind="model-usage"), MODEL_USAGE_HEADER.strip(), ""]
    for job in data.get("jobs") or []:
        if not isinstance(job, dict) or job.get("status") != "closed":
            continue
        role = job.get("role")
        if role not in PRIMARY_ROLES:
            continue
        stage_id = job.get("stage_id") or role
        profile = job.get("profile") or ""
        session_id = job.get("session_id") or ""
        if not session_id:
            continue
        model = job.get("model") or "unknown"
        usage = job.get("usage") or {}
        summary = {
            "session_id": session_id,
            "model": model,
            **usage,
        }
        time_cell = job.get("closed_at") or job.get("opened_at") or "unknown"
        if isinstance(time_cell, str) and "T" in time_cell:
            time_cell = time_cell.replace("T", " ").split("+")[0].split("Z")[0]
        reasoning = "expected policy / observed from export"
        evidence = f"jobs.yaml {job.get('id')} + hermes sessions export"
        row = markdown_row(
            summary,
            time_cell=resolve_time_cell("auto", summary) if usage else str(time_cell),
            stage_id=str(stage_id),
            action=str(role),
            profile=str(profile),
            role=str(profile).replace("dp-", "").replace("-", "_") or role,
            preset=preset,
            reasoning=reasoning,
            evidence=evidence,
        )
        lines.append(row)
    return "\n".join(lines) + "\n"


def render_review_summary(task_dir: Path) -> str:
    data = load_jobs(task_dir)
    lines = [
        GENERATED_HEADER.format(kind="review-summary"),
        "# Review session summary",
        "",
        "**Generated from `jobs.yaml` (v4).** Review worker and synthesis jobs only.",
        "",
        "| Job | Role | Reviewer | Target | Round | Session | Profile | Artifacts |",
        "|-----|------|----------|--------|-------|---------|---------|-----------|",
    ]
    for job in data.get("jobs") or []:
        if not isinstance(job, dict) or job.get("status") != "closed":
            continue
        if job.get("role") not in REVIEW_ROLES:
            continue
        reviewer = job.get("reviewer") or ""
        target = job.get("review_target") or ""
        rnd = job.get("review_round") or ""
        arts = job.get("artifacts_out") or {}
        art_cell = ", ".join(f"{k}={v}" for k, v in arts.items()) if isinstance(arts, dict) else ""
        lines.append(
            f"| `{job.get('id')}` | {job.get('role')} | {reviewer} | {target} | {rnd} | "
            f"`{job.get('session_id')}` | {job.get('profile')} | {art_cell} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kind", choices=("model-usage", "review-summary"))
    parser.add_argument("--task-dir", required=True)
    args = parser.parse_args()

    task_dir = Path(args.task_dir).resolve()
    if not is_v4_task(task_dir):
        print("render_jobs.py: jobs.yaml not found", file=sys.stderr)
        return 2

    try:
        if args.kind == "model-usage":
            text = render_model_usage(task_dir)
            default_out = default_model_usage_path(task_dir)
        else:
            text = render_review_summary(task_dir)
            default_out = default_review_summary_path(task_dir)
    except JobsStoreError as exc:
        print(f"render_jobs.py: {exc}", file=sys.stderr)
        return 2

    out_path = default_out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
